name: Serveo SSH Tunnel with User and Data Cache

on:
  workflow_dispatch:

jobs:
  serveo:
    runs-on: namespace-profile-test

    steps:
      # Step 1: Enable Namespace cache for /data (Namespace Cache Volume)
      - name: Enable /data cache (Namespace Cache Volume)
        if: always()
        continue-on-error: true
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          path: |
            /data

      # Step 2: Create new user for SSH access
      - name: Create 'serveo' user
        if: always()
        continue-on-error: true
        run: |
          echo "Creating user 'serveo'..."
          sudo useradd -m -s /bin/bash serveo || echo "User already exists"
          echo "serveo:serveo" | sudo chpasswd
          echo "User 'serveo' created with password 'serveo'."

      # Step 3: Reset root password
      - name: Reset root password to 'serveo'
        if: always()
        continue-on-error: true
        run: |
          echo "root:serveo" | sudo chpasswd
          echo "Root password reset complete."

      # Step 4: Open debug SSH session with tmate
      - name: Open debug SSH session (tmate)
        if: always()
        continue-on-error: true
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 350

      # Step 5: Save /data cache
   #   - name: Save /data cache
     #   if: always()
    #    continue-on-error: true
      #  uses: actions/cache@v4
     #   with:
        #  path: /data
          #key: ${{ runner.os }}-data-${{ github.run_number }}
