name: Linux VNC Setup

on:
  workflow_dispatch:  # Run manually

jobs:
  setup-vnc:
    runs-on: namespace-profile-default-arm64

    steps:
      - name: Install GNOME Desktop Environment
        run: |
          echo "Installing GNOME desktop environment..."
          sudo apt update
          sudo apt install -y ubuntu-desktop-minimal
          sudo apt install -y gnome-session gdm3
          echo "GNOME installation completed"
          
      - name: Install VNC Server
        run: |
          echo "Installing VNC server..."
          sudo apt install -y tightvncserver
          echo "VNC server installation completed"
          
      - name: Setup VNC Server
        run: |
          echo "Setting up VNC server..."
          # Create VNC password
          mkdir -p ~/.vnc
          echo "admin@123" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          
          # Create VNC startup script for GNOME
          cat > ~/.vnc/xstartup << 'EOF'
#!/bin/bash
export XKL_XMODMAP_DISABLE=1
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
exec gnome-session
EOF
          chmod +x ~/.vnc/xstartup
          
          # Start VNC server on port 8000 (display :8000)
          vncserver :8000 -geometry 1920x1080 -depth 24
          echo "VNC server started on port 8000"

      - name: Verify VNC Status
        run: |
          echo "Checking VNC server status..."
          # Wait a moment for services to start
          sleep 5
          # Check VNC processes
          ps aux | grep vnc | grep -v grep || echo "No VNC processes found"
          # Check VNC ports
          echo "Checking VNC port 8000:"
          netstat -an | grep :8000 || echo "Port 8000 not listening"
          lsof -i :8000 || echo "Port 8000 not in use (lsof)"
          # Check display
          echo "Checking display:"
          echo "DISPLAY: $DISPLAY"
          # Check VNC log
          echo "VNC log:"
          cat ~/.vnc/*.log 2>/dev/null | tail -10 || echo "No VNC log found"



      - name: Show Connection Information
        run: |
          echo "=== Linux VNC Server Connection Information ==="
          echo "VNC Server Status: TightVNC Server with GNOME"
          echo "VNC Port: 8000 (display :8000)"
          echo "VNC Password: admin@123"
          echo ""
          echo "Network Information:"
          echo "Primary IP Address:"
          IP_ADDR=$(hostname -I | awk '{print $1}' || echo "No IP found")
          echo "$IP_ADDR"
          echo ""
          echo "All network interfaces:"
          ip addr show | grep "inet " | grep -v 127.0.0.1
          echo ""
          echo "Connection Instructions:"
          echo "Use VNC client to connect to $IP_ADDR:8000 with password 'admin@123'"
          echo ""
          echo "Port Status Check:"
          netstat -an | grep :8000 | grep LISTEN || echo "Port 8000 not currently listening"
          echo "==============================================="
