name: macOS TigerVNC Setup

on:
  workflow_dispatch:  # Run manually

jobs:
  setup-vnc:
    runs-on: namespace-profile-mac

    steps:
      - name: Install TigerVNC
        run: |
          echo "Installing TigerVNC via Homebrew..."
          brew install tiger-vnc

      - name: Set VNC password
        run: |
          echo "Setting VNC password..."
          mkdir -p ~/.vnc
          # Find vncpasswd location
          which vncpasswd || find /opt/homebrew -name vncpasswd 2>/dev/null || echo "vncpasswd not found"
          # Use the correct path
          echo "admin@123" | /opt/homebrew/Cellar/tiger-vnc/1.15.0/bin/vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd

      - name: Start VNC server
        run: |
          echo "Starting TigerVNC server on display :1..."
          nohup /opt/homebrew/Cellar/tiger-vnc/1.15.0/bin/vncserver :1 -geometry 1920x1080 -depth 24 >/tmp/vncserver.log 2>&1 &

      - name: Verify VNC server running
        run: |
          echo "Checking VNC server process..."
          ps aux | grep Xtightvnc | grep -v grep || echo "VNC server not running"

      - name: Show Mac IP
        run: |
          echo "IP address:"
          ipconfig getifaddr en0 || ipconfig getifaddr en1 || echo "No IP found"
