name: macOS Screen Sharing Setup

on:
  workflow_dispatch:  # Run manually

jobs:
  setup-vnc:
    runs-on: namespace-profile-mac

    steps:
      - name: Enable macOS Screen Sharing
        run: |
          echo "Enabling macOS built-in Screen Sharing..."
          # Enable Screen Sharing (VNC) service
          sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.screensharing.plist
          # Enable Remote Management
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -clientopts -setvnclegacy -vnclegacy yes -clientopts -setvncpw -vncpw admin@123 -restart -agent -privs -all
          echo "Screen Sharing enabled successfully"

      - name: Verify Screen Sharing Status
        run: |
          echo "Checking Screen Sharing status..."
          # Check if Screen Sharing is running
          sudo launchctl list | grep screensharing || echo "Screen Sharing service not found in launchctl"
          # Check VNC port
          netstat -an | grep :5900 || echo "VNC port 5900 not listening"
          # Check Remote Management status
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -status

      - name: Configure Screen Sharing Settings
        run: |
          echo "Configuring Screen Sharing settings..."
          # Set display resolution (if possible)
          echo "Current display resolution:"
          system_profiler SPDisplaysDataType | grep Resolution || echo "Could not get display resolution"
          # Enable VNC viewers to control screen
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -allowAccessFor -allUsers -privs -all
          echo "Screen Sharing configuration completed"

      - name: Verify Screen Sharing Service
        run: |
          echo "Verifying Screen Sharing service is active..."
          # Check for Screen Sharing processes
          ps aux | grep -i screen | grep -v grep || echo "No screen sharing processes found"
          # Check for VNC/ARD processes
          ps aux | grep -i ard | grep -v grep || echo "No ARD processes found"
          # Final port check
          echo "Checking if VNC port 5900 is listening:"
          lsof -i :5900 || echo "Port 5900 not in use"

      - name: Show Connection Information
        run: |
          echo "=== macOS Screen Sharing Connection Information ==="
          echo "VNC Server Status: Screen Sharing Enabled"
          echo "VNC Port: 5900"
          echo "VNC Password: admin@123"
          echo ""
          echo "Network Information:"
          echo "Primary IP Address:"
          ipconfig getifaddr en0 || ipconfig getifaddr en1 || echo "No primary IP found"
          echo ""
          echo "All network interfaces:"
          ifconfig | grep "inet " | grep -v 127.0.0.1
          echo ""
          echo "To connect: Use VNC client to connect to <IP>:5900 with password 'admin@123'"
          echo "==============================================="
