name: macOS Screen Sharing Setup

on:
  workflow_dispatch:  # Run manually

jobs:
  setup-vnc:
    runs-on: namespace-profile-mac

    steps:
      - name: Enable macOS Screen Sharing
        run: |
          echo "Enabling macOS built-in Screen Sharing..."
          # Enable Screen Sharing via System Preferences method
          sudo defaults write /var/db/launchd.db/com.apple.launchd/overrides.plist com.apple.screensharing -dict Disabled -bool false
          # Enable VNC access
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -restart -agent -privs -all
          # Set VNC password and enable legacy VNC
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvnclegacy -vnclegacy yes -clientopts -setvncpw -vncpw admin@123
          # Start the Screen Sharing service
          sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.screensharing.plist 2>/dev/null || echo "Screen sharing plist already loaded"
          # Alternative method to start VNC
          sudo launchctl start com.apple.screensharing
          echo "Screen Sharing enabled successfully"

      - name: Verify Screen Sharing Status
        run: |
          echo "Checking Screen Sharing status..."
          # Wait a moment for services to start
          sleep 3
          # Check if Screen Sharing is running
          sudo launchctl list | grep screensharing || echo "Screen Sharing service not found in launchctl"
          # Check VNC port
          netstat -an | grep :5900 || echo "VNC port 5900 not listening"
          # Check with lsof
          lsof -i :5900 || echo "Port 5900 not in use (lsof)"
          # Check ARD Agent processes
          ps aux | grep ARDAgent | grep -v grep || echo "No ARDAgent processes found"
          # Try to get kickstart status with different approach
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -help | head -5 || echo "Kickstart help not available"

      - name: Force Start VNC Server
        run: |
          echo "Attempting to force start VNC server..."
          # Method 1: Enable VNC via System Preferences approach
          sudo defaults write /var/db/launchd.db/com.apple.launchd/overrides.plist com.apple.screensharing -dict Disabled -bool false
          # Method 2: Enable VNC legacy connections
          sudo defaults write /Library/Preferences/com.apple.RemoteDesktop.plist VNCLegacyConnectionsEnabled -bool true
          # Method 3: Set VNC password using proper encoding
          VNC_PASS_B64=$(echo -n "admin@123" | openssl base64)
          sudo defaults write /Library/Preferences/com.apple.RemoteDesktop.plist VNCPassword -data "$VNC_PASS_B64"
          # Method 4: Restart services
          sudo launchctl stop com.apple.screensharing 2>/dev/null || echo "Service not running"
          sudo launchctl start com.apple.screensharing
          # Method 5: Restart ARD Agent with VNC enabled
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -restart -agent -menu
          # Wait and check again
          sleep 8
          echo "Checking VNC port after force start:"
          netstat -an | grep :5900 || lsof -i :5900 || echo "VNC still not listening"
          # Check what's actually running
          echo "Screen sharing processes:"
          ps aux | grep -i screen | grep -v grep || echo "No screen processes"
          echo "Launchctl status:"
          sudo launchctl list | grep screen || echo "No screen services"
          
      - name: Configure Screen Sharing Settings
        run: |
          echo "Configuring Screen Sharing settings..."
          # Set display resolution (if possible)
          echo "Current display resolution:"
          system_profiler SPDisplaysDataType | grep Resolution || echo "Could not get display resolution"
          # Enable VNC viewers to control screen
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -allowAccessFor -allUsers -privs -all
          echo "Screen Sharing configuration completed"

      - name: Verify Screen Sharing Service
        run: |
          echo "Verifying Screen Sharing service is active..."
          # Check for Screen Sharing processes
          ps aux | grep -i screen | grep -v grep || echo "No screen sharing processes found"
          # Check for VNC/ARD processes
          ps aux | grep -i ard | grep -v grep || echo "No ARD processes found"
          # Final port check
          echo "Checking if VNC port 5900 is listening:"
          lsof -i :5900 || echo "Port 5900 not in use"

      - name: Show Connection Information
        run: |
          echo "=== macOS Screen Sharing Connection Information ==="
          echo "VNC Server Status: Screen Sharing Enabled"
          echo "VNC Port: 5900"
          echo "VNC Password: admin@123"
          echo ""
          echo "Network Information:"
          echo "Primary IP Address:"
          ipconfig getifaddr en0 || ipconfig getifaddr en1 || echo "No primary IP found"
          echo ""
          echo "All network interfaces:"
          ifconfig | grep "inet " | grep -v 127.0.0.1
          echo ""
          echo "To connect: Use VNC client to connect to <IP>:5900 with password 'admin@123'"
          echo "==============================================="
