name: macOS Screen Sharing Setup

on:
  workflow_dispatch:   # Run manually from Actions tab

jobs:
  enable-vnc:
    runs-on: namespace-profile-mac

    steps:
      - name: Enable Screen Sharing with VNC password
        run: |
          echo "Enabling macOS Screen Sharing (VNC)..."
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate -configure -access -on \
            -clientopts -setvnclegacy -vnclegacy yes \
            -clientopts -setvncpw -vncpw 'admin@123' \
            -restart -agent -privs -all

      - name: Verify ARDAgent process
        run: |
          echo "Checking ARDAgent process..."
          ps aux | grep ARDAgent | grep -v grep || echo "ARDAgent not running"

      - name: Verify Screen Sharing / Remote Management Status
        run: |
          echo "Checking launchctl for ARDAgent..."
          launchctl list | grep com.apple.RemoteDesktop || echo "No RemoteDesktop service loaded"

          echo "Checking if VNCAlwaysStartOnConsole is set..."
          defaults read /Library/Preferences/com.apple.RemoteManagement VNCAlwaysStartOnConsole || echo "VNC not configured"

          echo "Checking if ARDServiceActive is enabled..."
          defaults read /Library/Preferences/com.apple.RemoteManagement ARDServiceActive || echo "Remote Management not active"

      - name: Show IP Address of macOS runner
        run: |
          echo "Finding IP address..."
          ipconfig getifaddr en0 || ipconfig getifaddr en1 || echo "No IP found"
