name: Linux VNC Setup

on:
  workflow_dispatch:

jobs:
  setup-vnc:
    runs-on: namespace-profile-default-arm64

    steps:
      - name: Install Desktop Environment
        run: |
          sudo apt update
          sudo apt install -y ubuntu-desktop-minimal gnome-session gdm3

      - name: Install VNC Server
        run: |
          sudo apt install -y tightvncserver

      - name: Setup VNC Server
        run: |
          mkdir -p ~/.vnc
          echo "admin@123" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          
          cat > ~/.vnc/xstartup << 'EOF'
#!/bin/bash
export XKL_XMODMAP_DISABLE=1
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
exec gnome-session
EOF
          chmod +x ~/.vnc/xstartup
          
          vncserver :8000 -geometry 1024x768 -depth 16

      - name: Setup Pinggy Tunnel
        run: |
          wget https://s3.ap-south-1.amazonaws.com/public.pinggy.binaries/cli/v0.2.5/linux/arm64/pinggy
          chmod +x pinggy
          nohup ./pinggy -p 443 -R0:localhost:8000 -o StrictHostKeyChecking=no -o ServerAliveInterval=30 2CKLdGYp967+force+tcp@free.pinggy.io > pinggy.log 2>&1 &
          sleep 10

      - name: Show Connection Info
        run: |
          echo "VNC Server: localhost:8000"
          echo "Password: admin@123"
          echo "Resolution: 1024x768"
          IP_ADDR=$(hostname -I | awk '{print $1}')
          echo "Local IP: $IP_ADDR:8000"
          TUNNEL_URL=$(grep -o 'tcp://[^[:space:]]*' pinggy.log 2>/dev/null | head -1)
          if [ -n "$TUNNEL_URL" ]; then
            echo "Remote URL: $TUNNEL_URL"
          fi